// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfhatssdbnhanzsvabnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmaGF0c3NkYm5oYW56c3ZhYm5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDIwMjcsImV4cCI6MjA2NjE3ODAyN30.kPhQWbMHpZph5thro4_QUfdFcmCA0Pm7rjQYSxawQrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);